title: Rants
description: Various rants on software, architecture, and engineering.
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/johnjoeallen" }
